#!/usr/bin/env node
/**
 * Builds the self-contained static export used for the shareable preview.
 *
 * `next build` has no flag for pointing at a different config file, and the
 * export settings must not live in `next.config.ts` — see the note there about
 * Railway's builder. So this swaps the config in for the length of the build
 * and always puts the original back, including on failure or Ctrl-C.
 *
 * Output lands in `out/`, with relative asset URLs so it works when served
 * from a sub-path.
 */
import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const CONFIG = resolve("next.config.ts");
const BACKUP = resolve("next.config.ts.orig");

const EXPORT_CONFIG = `import type { NextConfig } from "next";

// Generated by scripts/build-preview.mjs for the duration of one build.
// Not committed: the real config is restored when the build finishes.
const nextConfig: NextConfig = {
  output: "export",
  assetPrefix: ".",
  images: { unoptimized: true },
};

export default nextConfig;
`;

function restore() {
  if (!existsSync(BACKUP)) return;
  copyFileSync(BACKUP, CONFIG);
  rmSync(BACKUP);
}

if (existsSync(BACKUP)) {
  console.error(
    `${BACKUP} already exists — a previous preview build did not finish.\n` +
      "Check next.config.ts, restore it from that file if needed, then delete it.",
  );
  process.exit(1);
}

// Survive an interrupt, so the repo is never left holding the export config.
for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => {
    restore();
    process.exit(1);
  });
}

const original = readFileSync(CONFIG, "utf8");

let status = 1;
try {
  copyFileSync(CONFIG, BACKUP);
  writeFileSync(CONFIG, EXPORT_CONFIG);

  rmSync(resolve("out"), { recursive: true, force: true });
  status = spawnSync("npx", ["next", "build"], {
    stdio: "inherit",
    env: { ...process.env, STATIC_EXPORT: "1" },
  }).status ?? 1;
} finally {
  restore();
}

if (status === 0 && !existsSync(resolve("out", "index.html"))) {
  console.error("Build succeeded but out/index.html is missing.");
  status = 1;
}

// A guard against exactly the bug this script exists to avoid: the deployed
// config must come back byte-for-byte.
if (readFileSync(CONFIG, "utf8") !== original) {
  console.error("next.config.ts was not restored — fix it before committing or deploying.");
  process.exit(1);
}

process.exit(status);
